//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace G03_3S
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documentacao
    {
        public int IdDocumento { get; set; }
        public int UsuarioAutor { get; set; }
        public byte[] Documento { get; set; }
        public string NomeDocumento { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
